#! /bin/sh

### BEGIN INIT INFO
# Provides:        bath
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description:  
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin
export QT_QPA_PLATFORM=eglfs
export LC_ALL=cs_CZ.UTF-8
# physical width and height units are mm

# for the official Pi 7" touchscreen
export QT_QPA_EGLFS_PHYSICAL_WIDTH=155
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=86


DAEMON=/home/root/bath_mdrp
PIDFILE=/var/run/bath.pid

# bath init.d script for bath
test -x $DAEMON || exit 0

# Source function library.
. /etc/init.d/functions

# Functions to do individual actions
startdaemon(){
	# The -g option allows ntpd to step the time to correct it just
	# once.  The daemon will exit if the clock drifts too much after
	# this.  If ntpd seems to disappear after a while assume TICKADJ
	# above is set to a totally incorrect value.
	echo -n "Starting bath: "
	start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -u root:root -p $PIDFILE "$@"
	echo "done"

stopdaemon(){
	echo -n "Stopping bath: "
	start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
	echo "done"
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  	stopdaemon
	;;
  force-reload)
  	stopdaemon
	startdaemon -g
	;;
  restart)
  	# Don't reset the tick here
	stopdaemon
	startdaemon -g
	;;
  reload)
  	# Must do this by hand, but don't do -g
	stopdaemon
	startdaemon
	;;
  status)
	status /usr/bin/bath_srot;
	exit $?
	;;
  *)
	echo "Usage: bath { start | stop | status | restart | reload }" >&2
	exit 1
	;;
esac

exit 0
